import { cosmicPalette } from './cosmicPalette.js';

export const solarSystem = [
  {
    id: 'mercury',
    name: 'Mercury',
    color: '#9f8c7d',
    atmosphereColor: cosmicPalette.plasmaOrange,
    semiMajorAxisAu: 0.387,
    orbitalPeriodDays: 87.97,
    rotationHours: 1407.6,
    axialTiltDeg: 0.03,
    diameterKm: 4879,
    gravityMs2: 3.7,
    massEarths: 0.055,
    moonCount: 0,
    distanceFromSunKm: '57.9 million',
    fact: 'Mercury’s solar day lasts 176 Earth days because its 3:2 spin-orbit resonance makes noon crawl across the sky.',
  },
  {
    id: 'venus',
    name: 'Venus',
    color: '#d4ad6e',
    atmosphereColor: '#f6d6a8',
    semiMajorAxisAu: 0.723,
    orbitalPeriodDays: 224.7,
    rotationHours: -5832.5,
    axialTiltDeg: 177.4,
    diameterKm: 12104,
    gravityMs2: 8.87,
    massEarths: 0.815,
    moonCount: 0,
    distanceFromSunKm: '108.2 million',
    fact: 'Venus rotates backward, so on its surface the Sun would appear to rise in the west and set in the east.',
  },
  {
    id: 'earth',
    name: 'Earth',
    color: '#3b82f6',
    atmosphereColor: cosmicPalette.nebulaBlue,
    semiMajorAxisAu: 1,
    orbitalPeriodDays: 365.25,
    rotationHours: 23.93,
    axialTiltDeg: 23.44,
    diameterKm: 12742,
    gravityMs2: 9.81,
    massEarths: 1,
    moonCount: 1,
    distanceFromSunKm: '149.6 million',
    fact: 'Earth’s oceans and atmosphere create a narrow habitability shell only a few tens of kilometers thick on planetary scales.',
  },
  {
    id: 'mars',
    name: 'Mars',
    color: '#b45536',
    atmosphereColor: '#ff8b5a',
    semiMajorAxisAu: 1.524,
    orbitalPeriodDays: 687,
    rotationHours: 24.62,
    axialTiltDeg: 25.19,
    diameterKm: 6779,
    gravityMs2: 3.71,
    massEarths: 0.107,
    moonCount: 2,
    distanceFromSunKm: '227.9 million',
    fact: 'Olympus Mons on Mars rises about 22 kilometers high, the tallest large volcano known in the solar system.',
  },
  {
    id: 'jupiter',
    name: 'Jupiter',
    color: '#d9b38c',
    atmosphereColor: '#ffb36d',
    semiMajorAxisAu: 5.203,
    orbitalPeriodDays: 4331,
    rotationHours: 9.93,
    axialTiltDeg: 3.13,
    diameterKm: 139820,
    gravityMs2: 24.79,
    massEarths: 317.8,
    moonCount: 95,
    distanceFromSunKm: '778.5 million',
    fact: 'Jupiter emits more heat than it receives from the Sun because it is still slowly contracting under its own gravity.',
  },
  {
    id: 'saturn',
    name: 'Saturn',
    color: '#d8c18e',
    atmosphereColor: '#ffe3a6',
    semiMajorAxisAu: 9.537,
    orbitalPeriodDays: 10747,
    rotationHours: 10.7,
    axialTiltDeg: 26.73,
    diameterKm: 116460,
    gravityMs2: 10.44,
    massEarths: 95.16,
    moonCount: 146,
    distanceFromSunKm: '1.43 billion',
    fact: 'Saturn would float in a large enough ocean because its average density is lower than liquid water.',
  },
  {
    id: 'uranus',
    name: 'Uranus',
    color: '#86d5ff',
    atmosphereColor: '#b6f1ff',
    semiMajorAxisAu: 19.191,
    orbitalPeriodDays: 30589,
    rotationHours: -17.24,
    axialTiltDeg: 97.77,
    diameterKm: 50724,
    gravityMs2: 8.69,
    massEarths: 14.54,
    moonCount: 28,
    distanceFromSunKm: '2.87 billion',
    fact: 'Uranus spins on its side, likely after a titanic impact early in solar-system history.',
  },
  {
    id: 'neptune',
    name: 'Neptune',
    color: '#4a66ff',
    atmosphereColor: '#7aa2ff',
    semiMajorAxisAu: 30.07,
    orbitalPeriodDays: 59800,
    rotationHours: 16.11,
    axialTiltDeg: 28.32,
    diameterKm: 49244,
    gravityMs2: 11.15,
    massEarths: 17.15,
    moonCount: 16,
    distanceFromSunKm: '4.5 billion',
    fact: 'Neptune’s winds can exceed 2,000 kilometers per hour, some of the fastest sustained atmospheric flows in the solar system.',
  },
];

export const solarScale = {
  radiusCompression: 0.0028,
  orbitCompression: 4.8,
  asteroidCount: 700,
};
