export const spectralClasses = [
  {
    key: 'O',
    label: 'Blue supergiant',
    color: '#9bb0ff',
    temperatureKelvin: '30,000+',
    probability: 0.01,
  },
  {
    key: 'B',
    label: 'Blue-white giant',
    color: '#aabfff',
    temperatureKelvin: '10,000-30,000',
    probability: 0.02,
  },
  {
    key: 'A',
    label: 'White main-sequence',
    color: '#cad7ff',
    temperatureKelvin: '7,500-10,000',
    probability: 0.06,
  },
  {
    key: 'F',
    label: 'Yellow-white star',
    color: '#f8f7ff',
    temperatureKelvin: '6,000-7,500',
    probability: 0.1,
  },
  {
    key: 'G',
    label: 'Solar-type star',
    color: '#fff4ea',
    temperatureKelvin: '5,200-6,000',
    probability: 0.17,
  },
  {
    key: 'K',
    label: 'Orange dwarf',
    color: '#ffd2a1',
    temperatureKelvin: '3,700-5,200',
    probability: 0.24,
  },
  {
    key: 'M',
    label: 'Red dwarf',
    color: '#ffcc6f',
    temperatureKelvin: '2,400-3,700',
    probability: 0.4,
  },
];

export const brightStars = [
  { name: 'Sirius', spectralType: 'A1V', distanceLy: 8.6, position: [0.12, 0.18] },
  { name: 'Canopus', spectralType: 'A9II', distanceLy: 310, position: [0.24, 0.12] },
  { name: 'Arcturus', spectralType: 'K1.5III', distanceLy: 36.7, position: [0.33, 0.17] },
  { name: 'Vega', spectralType: 'A0V', distanceLy: 25, position: [0.44, 0.14] },
  { name: 'Capella', spectralType: 'G8III', distanceLy: 42.9, position: [0.56, 0.12] },
  { name: 'Rigel', spectralType: 'B8Ia', distanceLy: 860, position: [0.68, 0.16] },
  { name: 'Procyon', spectralType: 'F5IV-V', distanceLy: 11.5, position: [0.79, 0.12] },
  { name: 'Achernar', spectralType: 'B6Vep', distanceLy: 139, position: [0.89, 0.18] },
  { name: 'Betelgeuse', spectralType: 'M1-2Ia-ab', distanceLy: 548, position: [0.08, 0.3] },
  { name: 'Hadar', spectralType: 'B1III', distanceLy: 390, position: [0.2, 0.28] },
  { name: 'Altair', spectralType: 'A7V', distanceLy: 16.7, position: [0.31, 0.3] },
  { name: 'Aldebaran', spectralType: 'K5III', distanceLy: 65, position: [0.42, 0.28] },
  { name: 'Spica', spectralType: 'B1V', distanceLy: 250, position: [0.52, 0.31] },
  { name: 'Antares', spectralType: 'M1.5Iab-Ib', distanceLy: 554, position: [0.62, 0.28] },
  { name: 'Pollux', spectralType: 'K0III', distanceLy: 33.8, position: [0.73, 0.31] },
  { name: 'Fomalhaut', spectralType: 'A3V', distanceLy: 25.1, position: [0.86, 0.27] },
  { name: 'Deneb', spectralType: 'A2Ia', distanceLy: 2615, position: [0.1, 0.43] },
  { name: 'Regulus', spectralType: 'B8IVn', distanceLy: 79, position: [0.21, 0.45] },
  { name: 'Castor', spectralType: 'A1V', distanceLy: 51.6, position: [0.32, 0.41] },
  { name: 'Bellatrix', spectralType: 'B2III', distanceLy: 250, position: [0.42, 0.44] },
  { name: 'Saiph', spectralType: 'B0.5Ia', distanceLy: 720, position: [0.54, 0.43] },
  { name: 'Mimosa', spectralType: 'B0.5III', distanceLy: 280, position: [0.66, 0.42] },
  { name: 'Alnilam', spectralType: 'B0Ia', distanceLy: 2000, position: [0.76, 0.45] },
  { name: 'Alnair', spectralType: 'B7IV', distanceLy: 101, position: [0.88, 0.42] },
  { name: 'Polaris', spectralType: 'F7Ib', distanceLy: 433, position: [0.12, 0.57] },
  { name: 'Dubhe', spectralType: 'K0III', distanceLy: 123, position: [0.24, 0.58] },
  { name: 'Merak', spectralType: 'A1V', distanceLy: 79.7, position: [0.34, 0.56] },
  { name: 'Phecda', spectralType: 'A0V', distanceLy: 83.2, position: [0.44, 0.58] },
  { name: 'Megrez', spectralType: 'A3V', distanceLy: 80.5, position: [0.55, 0.56] },
  { name: 'Alioth', spectralType: 'A0pCr', distanceLy: 81, position: [0.65, 0.58] },
  { name: 'Mizar', spectralType: 'A2V', distanceLy: 82.9, position: [0.76, 0.56] },
  { name: 'Alkaid', spectralType: 'B3V', distanceLy: 104, position: [0.88, 0.59] },
  { name: 'Denebola', spectralType: 'A3V', distanceLy: 35.9, position: [0.14, 0.72] },
  { name: 'Scheat', spectralType: 'M2.5II', distanceLy: 196, position: [0.24, 0.75] },
  { name: 'Markab', spectralType: 'B9III', distanceLy: 133, position: [0.37, 0.71] },
  { name: 'Enif', spectralType: 'K2Ib', distanceLy: 670, position: [0.49, 0.75] },
  { name: 'Algol', spectralType: 'B8V', distanceLy: 90, position: [0.6, 0.72] },
  { name: 'Alpheratz', spectralType: 'B8IVp', distanceLy: 97, position: [0.71, 0.76] },
  { name: 'Hamal', spectralType: 'K2III', distanceLy: 66, position: [0.82, 0.72] },
  { name: 'Almach', spectralType: 'K3IIb', distanceLy: 350, position: [0.9, 0.78] },
];

export const iauConstellationOverlay = [
  ['Dubhe', 'Merak'],
  ['Merak', 'Phecda'],
  ['Phecda', 'Megrez'],
  ['Megrez', 'Alioth'],
  ['Alioth', 'Mizar'],
  ['Mizar', 'Alkaid'],
  ['Polaris', 'Vega'],
  ['Vega', 'Altair'],
  ['Betelgeuse', 'Rigel'],
  ['Betelgeuse', 'Bellatrix'],
  ['Bellatrix', 'Saiph'],
  ['Saiph', 'Rigel'],
  ['Sirius', 'Aldebaran'],
  ['Aldebaran', 'Betelgeuse'],
  ['Deneb', 'Altair'],
  ['Altair', 'Alnair'],
  ['Denebola', 'Regulus'],
  ['Markab', 'Scheat'],
  ['Scheat', 'Alpheratz'],
  ['Hamal', 'Algol'],
];
